### PR TITLE
[12.0][MIG] l10n_be_mis_reports: Migration to 12.0

### PR DESCRIPTION
**Pull request by elouan-lb**

### CODE REVIEW

**Review by houssine78 — APPROVED** [review]

**Comment by houssine78** [comment]
@sbidoul could you have a look at this PR it has also been tested by @vdewulf 

travis fail on a depedency on mis_builder. I don't know what is missing and how to fix. We can try to fix it with some guidance ;)

**Comment by sbidoul** [comment]
Thanks for this migration! Adding [oca_dependencies.txt](https://github.com/coopiteasy/l10n-belgium/blob/11.0/oca_dependencies.txt) should fix the travis issue.

**Comment by elouan-lb** [comment]
Dear @pedrobaeza, it's my first PR on the OCA, I signed the CLA but made a mistake in my git configuration's email. Does it now seems fixed to you ?

**Comment by sbidoul** [comment]
@elouan-lb you CLA is ok, thanks! The bot may take some time to notice it.

**Comment by houssine78** [comment]
@elouan-lb can you add the oca_dependencies.txt as done [here](https://github.com/coopiteasy/l10n-belgium/blob/11.0/oca_dependencies.txt) thanks !

**Comment by elouan-lb** [comment]
> @elouan-lb can you add the oca_dependencies.txt as done [here](https://github.com/coopiteasy/l10n-belgium/blob/11.0/oca_dependencies.txt) thanks !

Done !

**Comment by sbidoul** [comment]
Looks good, thanks!

**Comment by houssine78** [comment]
thanks !

**Pull request merged**
