### PR TITLE
[ADD] P&L and BS reports for coorporations w/o shares and ASBL

### LINKED ISSUE #185: In which modules should I add new mis-reports templates?
An accountant has made fixed and improved versions of mis-reports templates (Balance sheet and P&L) for specific legal form:
- a set of template for "Sociétés sans capital" (cooperatives, SRL)
- a set of templates for ASBL

We want to put them in modules in this repo. Should we add two new modules (one for each legal form) ? Or should we add them in the existing module of templates ?
@sbidoul @vdewulf

### PR DESCRIPTION
**Pull request by robinkeunen**
These reports were generated based on data provided by our accountant. The original template can be found [here](https://docs.google.com/spreadsheets/d/10AKN579kFbw5TFrNVmw0j0puH3P7pw-D/edit#gid=159598607)

8 reports are added :

- Belgium Balance Sheet - ASBL (Full Model)
- Belgium Balance Sheet - ASBL (Short Model)
- Belgium Balance Sheet - Corporation w/o Share (Full Model)
- Belgium Balance Sheet - Corporation w/o Share (Short Model)
- Belgium Balance Sheet - Corporation w/o Share (Micro Model)
- Belgium P&L - Corporation **w/o** Share (Full Model)
- Belgium P&L - Corporation **w/o** Share (Short Model)
- Belgium P&L - Corporation **w/o** Share (Micro Model)

I'm still waiting for a few French to English translations.

TODO : add translations to French and Dutch.

### CODE REVIEW

**Comment by sbidoul** [comment]
Nice! Just a question: should we not keep the previous models and change their label to mention they are deprecated, or pre-2018 (not sure about the date).

**Comment by robinkeunen** [comment]
Thx! I made a mistake in the PR description : I only added templates for ASBL and Corporation **w/o** shares. I'm not aware that the corporation models are deprecated, I'll ask our accountant if that's the case.

In this PR, I only renamed the files and labels for the corporation templates.

**Comment by robinkeunen** [comment]
Indeed, I did not understand that the reports provided replaced the previous ones. I'll rename them as you suggest!

**Comment by robinkeunen** [comment]
This work is still ongoing, I'm having troubles getting answers from our accountant;

**Comment by robinkeunen** [comment]
cf https://github.com/OCA/l10n-belgium/pull/203

**Pull request closed without merging**
