### PR TITLE
[17.0][MIG] account_statement_import_coda

### PR DESCRIPTION
**Pull request by antonioburic**

### CODE REVIEW

**Review by houssine78 — APPROVED** [review]
LGTM

**Comment by houssine78** [comment]
@sbidoul can we apply no stale label on this PR ? thank you !

**Comment by sbidoul** [comment]
I compared with v16 using `pip-wheel-diff "odoo-addon-account_statement_import_coda==16.0.*" "git+https://github.com/oca/l10n-belgium@refs/pull/223/head#subdirectory=account_statement_import_coda"`. LGTM.

/ocabot merge nobump

**Pull request merged**
