### PR TITLE
intrastat readme

### PR DESCRIPTION
**Pull request by luc-demeyer**

### CODE REVIEW

**Comment by luc-demeyer** [comment]
@sbidoul 
oca-gen-addon-readme doesn't want to generate the README.rst file.
I don't have a clue what wrong with the input.
Can you help ?

**Comment by sbidoul** [comment]
I think the issue is in INSTALL.rst. There is a conflict in rst title levels with the titles that are autogenerated by the README template. If you use `~` for title underlines in README fragments, it should work.

**Comment by luc-demeyer** [comment]
@sbidoul 
Thanks a lot for your suggestion. Issue fixed !

**Pull request merged**
