### PR TITLE
[10.0] add kbo_bce_number

### PR DESCRIPTION
**Pull request by luc-demeyer**
This module contains the 10.0 port of the KBO/BCE number functionality which is available in the 8.0 l10n_be_partner module.

### CODE REVIEW

**Comment by sbidoul** [comment]
@lmignon @rousseldenis one of you would like to review this?

Also should we converge with #41 ? Merge the modules ? Or make one module per identifier ?

**Comment by luc-demeyer** [comment]
We should not merge with  #41. 
KBO/BCE number is for companies, id number for persons, hence different requirement.

**Review by sbidoul — APPROVED** [review]
LGTM

**Comment by sbidoul** [comment]
I fixed travis on the 10.0 branch. 

/ocabot merge patch

**Comment by sbidoul** [comment]
Thanks @luc-demeyer! better merging late than never I guess :)

**Comment by luc-demeyer** [comment]
@sbidoul 
Thanks.
I have submitted https://github.com/OCA/l10n-belgium/pull/86 in order to have the latest patches included in this module.
I'll try to find a bit of time in the coming days to also make PRs for the versions 11.0,12.0 & 13.0 of this module so that I can remove this module from the noviat repos in apps.odoo.com in order to avoid an apps store conflict.
Once these are merged I can also submit the versions 10.0 - 13.0 of the l10n_be_intrastat_product module.

**Comment by gva-acsone** [comment]
Hello @luc-demeyer ,
Did you already start working on the V12.0 version of the module? 

If not, we can make a PR to migrate the module to V12, as we need it for one of our customers. 

Regards

**Comment by luc-demeyer** [comment]
this module is available for all versions, cf :
https://github.com/luc-demeyer/noviat-apps/tree/11.0
https://github.com/Noviat/noviat-apps/tree/12.0
https://github.com/Noviat/noviat-apps/tree/13.0

If you have time, feel free to take the 11.0, 12.0 and 13.0 ports and make OCA PR's (I'll review & remove them from the noviat git repos after merge in OCA l10n_be).

**Pull request merged**
