### PR TITLE
8.0 account_companyweb refactor

### PR DESCRIPTION
**Pull request by jbaudoux**
The main purpose of this code refactoring is to store the companyweb fetched data. Each API call consumes credits, so it is important to store in odoo the result. The transient wizard is now changed by additional fields directly on res.partner and visible on a new tab after the accounting tab.
Actions to refresh data have been added.
Some bugs have been fixed.

### CODE REVIEW

**Comment by sbidoul** [comment]
@jbaudoux can you look after the pylint issues, check why there is a conflict?

**Comment by jbaudoux** [comment]
@sbidoul there was some lines to long and conflits on translation that I solved by rebasing the branch

**Comment by jbaudoux** [comment]
@sbidoul This module is in production for few months and working fine. Can this refactor get merged?

**Comment by sbidoul** [comment]
@jbaudoux it needs to be reviewed according to the OCA process. I see the branch has conflicts, can you rebase?

@adrienpeiffer when you have a moment, could you review this?

**Comment by gurneyalex** [comment]
needs rebasing

**Comment by jbaudoux** [comment]
We have added the possibility to track customers and get updates from company web.
+ rebased branch and ported code to new api

**Comment by jbaudoux** [comment]
@sylvainvh Can you put back your old email as second email in your github account?

**Comment by sbidoul** [comment]
@jbaudoux we have got some financing to re-do the companyweb module for v12, 13 and 14.
We are going to do a `companyweb_base`, with only the most basic feature (downloading company information on user request, using the new cw web service), and advanced feature can then be built on top of it.
We plan to use the same `cweb_*` field names as in this PR for compatibility.

BTW, is this one ready to merge in v8 ?

cc/ @xavier-bouquiaux

**Comment by jbaudoux** [comment]
@sbidoul Thanks for the notice. This module works well for downloading company data. And you can also enable company tracking to be informed of updates (instead of pulling).
It probably now needs rebasing and some love to have it green

**Pull request closed without merging**
