### PR TITLE
[11.0][MIG] l10n_be_vat_reports: VAT Listing and VAT Intra

### PR DESCRIPTION
**Pull request by robinkeunen**
While we're at it, based on the freshly merged https://github.com/OCA/l10n-belgium/pull/85.

Backport of module l10n_be_vat_reports from v12, this module declares VAT Listing and VAT Intra reports for the Belgium administration.

### CODE REVIEW

**Comment by sbidoul** [comment]
@robinkeunen can you check travis ?

**Review by houssine78 — APPROVED** [review]

**Comment by houssine78** [comment]
LGTM

**Comment by robinkeunen** [comment]
@sbidoul all green over here, can you take a look?

**Comment by sbidoul** [comment]
LGTM. Thanks!

/ocabot merge patch

**Pull request merged**
