### PR TITLE
8.0 coa multilang

### PR DESCRIPTION
**Pull request by jbaudoux**
Ported module l10n_be_coa_multilang from https://github.com/luc-demeyer/noviat-apps.git and split into:
- l10n_be_coa_multilang (replace l10n_be for multilang support)
- l10n_be_financial_reports (latest statement and reports)
- l10n_be_vat_declaration (latest vat declaration)

Done during Belgian Code Sprint of 2015-08-28

### CODE REVIEW

**Comment by sbidoul** [comment]
CLA OK. I don't understand why the bot complains.

**Comment by gaelrabier** [comment]
I just mailed them to link my github account, done.

Gaël Rabier
gael@niboo.be mailto:gael@niboo.be
+32 487 027 913

**Comment by sbidoul** [comment]
@jbaudoux there are companyweb commits in this PR. They don't belong here. Can you rebase and propose the companyweb improvements in another PR?

**Comment by jbaudoux** [comment]
@sbidoul You're right, I didn't branch from the right remote. I just rebased this PR on OCA#8.0 and repushed all our changed.

**Pull request closed without merging**
