### PR TITLE
[14.0][MIG] l10n_be_mis_reports: Migration to 14.0

### PR DESCRIPTION
**Pull request by joao-p-marques**
Standard migration to v14.

@Tecnativa 
TT31596

ping @pedrobaeza @victoralmau @sbidoul

### CODE REVIEW

**Comment by joao-p-marques** [comment]
Travis error seems unrelated, coming from `companyweb_base`

**Review by victoralmau — APPROVED** [review]
Code review OK.
Is it possible to purge translations?

**Review by pedrobaeza — APPROVED** [review]

**Comment by sbidoul** [comment]
That's not going to work as there is a test issue in another module that we still not fix.

**Comment by sbidoul** [comment]
We have fixed the companyweb_base test, this should now be green.

/ocabot merge patch

**Pull request merged**
