### PR TITLE
add l10n_be_partner

### PR DESCRIPTION
**Pull request by luc-demeyer**

### CODE REVIEW

**Comment by sbidoul** [comment]
setting WIP pending refactoring

**Comment by luc-demeyer** [comment]
This module has now been refactored (as discussed during recent belgian OCA code sprint):
- non-belgian partner titles removed
- OCA guidelines adherence

The WIP label can be removed.

**Comment by pedrobaeza** [comment]
@sbidoul can you please review this?

**Comment by pedrobaeza** [comment]
Any news on this?

**Comment by pedrobaeza** [comment]
Closing as no answer

**Pull request closed without merging**
