### PR TITLE
[16.0][ADD] New module l10n_be_bpost_address_autocomplete

### PR DESCRIPTION
**Pull request by kouffsamuel**
This PR allows you to autocomplete partner's address using the bpost API.

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
I didn't know Bpost had this kind of webservices available. Really interesting module

This works very well except for one case. Cases where you have a box or supplement on your address do not work (Example below).

Here is the search:

Capture d'écran 2023-04-25 215632

Here is the result:

image

**Comment by kouffsamuel** [comment]
@jdidderen-noviat Thanks for your feedback, i will fix that.

**Comment by luc-demeyer** [comment]
Can you rename module to l10n_be_bpost_address_autocomplete ?

**Review by lmignon — APPROVED** [review]
GREAT! LGTM (Code review + Functional tests)

**Review by ghost — APPROVED** [review]
LGTM
Nice work :)

**Comment by sbidoul** [comment]
@kouffsamuel could you rebase without the `setup/_metapackage` directory that creates conflicts? It will be re-generated by the bot. Then I'll merge.

**Comment by kouffsamuel** [comment]
> @kouffsamuel could you rebase without the `setup/_metapackage` directory that creates conflicts? It will be re-generated by the bot. Then I'll merge.

I tried to remove it. But it's weird because when I check the commit, the folder is already removed.

**Comment by sbidoul** [comment]
Hm. I think the conflict is because you try to remove these two files that are on the 16.0 branch. You should leave them untouched.

**Comment by sbidoul** [comment]
Perfect, thanks a lot for this excellent work!

/ocabot merge nobump

**Pull request merged**
