### PR TITLE
[FIX] Api improvement, get_import_type_selection has been renamed in _ge...

### PR DESCRIPTION
**Pull request by lmignon**
...t_import_type_selection in commit https://github.com/OCA/bank-statement-reconcile/commit/c6e8ea55006cdc900b882b9e8e424395fab9708e

### CODE REVIEW

**Comment by laetitia-gangloff** [comment]
:+1:

**Comment by Cedric-Pigeon** [comment]
:+1:

**Comment by JonathanNEMRY** [comment]
:+1:

**Comment by sbidoul** [comment]
Merging quickly as this is an obvious fix to adapt to changes outside of this project.

**Pull request merged**
