### PR TITLE
[11.0][MIG] bank_statement_import_coda

### PR DESCRIPTION
**Pull request by RobinetDenisAcsone**
Migration of the bank_statement_import_coda addon from https://github.com/OCA/l10n-belgium/pull/54

Beside the python 3 and readme changes, there is a small fix in the tests, when journals are not in EUR, which doesn't happen in the other branches because l10n_be is installed.

### CODE REVIEW

**Comment by codingisacopingstrategy** [comment]
Hello! Great! What’s the status of this? Could I try it out? My accountant has been very grumpy at me ever since we installed them an Odoo without CODA parsing!

If I wanted to test it what would be the text that I add to my requirements.txt?

Thanks,

**Comment by lmignon** [comment]
@codingisacopingstrategy Here it's what you can add to your requirements.txt file to install the branch on which this PR is based.
```
-e git+https://github.com/acsone/l10n-belgium.git@11.0-mig-bank_statement_import_coda#egg=odoo10-addon-account_bank_statement_import_coda&subdirectory=setup/account_bank_statement_import_coda
```

**Comment by codingisacopingstrategy** [comment]
Thanks @lmignon ! Is the part `#egg=odoo10-addon` correct? Shouldn’t that be `odoo11`

When installing I get the warning:

    Running setup.py (path:/home/odoo/venv/src/odoo10-addon-account-bank-statement-import-coda/setup/account_bank_statement_import_coda/setup.py) egg_info for package odoo10-addon-account-bank-statement-import-coda produced metadata for project name odoo11-addon-account-bank-statement-import-coda. Fix your #egg=odoo10-addon-account-bank-statement-import-coda fragments.

I changed the command to 

    -e git+https://github.com/acsone/l10n-belgium.git@11.0-mig-bank_statement_import_coda#egg=odoo11-addon-account_bank_statement_import_coda&subdirectory=setup/account_bank_statement_import_coda

And no longer get the warning.

**Comment by codingisacopingstrategy** [comment]
I changed the command to 

    -e git+https://github.com/acsone/l10n-belgium.git@11.0-mig-bank_statement_import_coda#egg=odoo11-addon-account_bank_statement_import_coda&subdirectory=setup/account_bank_statement_import_coda

I no longer get this warning. Can’t find the module in Odoo though… maybe I didn’t get my Odoo to restart properly

screen shot 2018-12-17 at 08 18 14

**Comment by codingisacopingstrategy** [comment]
OK, so I managed to install the module! Just for a moment I couldn’t see it but I’d forgotten about the “update module list” option.

I’ll have to ask my bookkeeper to try the module, as I don’t have the CODA files myself.

I do see a first hiccup: when I click import a bank statement, it says: `supported formats: [blank]`
Where before it said: `supported formats: OXF`

Maybe it’s a localisation thing? I tried in both NL and FR

screen shot 2018-12-17 at 19 07 40

**Comment by RobinetDenisAcsone** [comment]
@codingisacopingstrategy That's true, CODA isn't show in the form, It's not a localization thing, I will add it.

For the OFX, it shouldn't be related to this addons, it was added by another addon (maybe [account_bank_statement_import_ofx](https://github.com/OCA/bank-statement-import/tree/11.0/account_bank_statement_import_ofx)), is it still installed?

**Comment by codingisacopingstrategy** [comment]
@RobinetDenisAcsone it’s from a module that was installed standard with Odoo 11, called “Import de Relevé de Compte Bancaire” (I think it’s technical name is `account_bank_statement_import` but I’m not sure how to check that)

screen shot 2018-12-18 at 11 19 24

**Comment by RobinetDenisAcsone** [comment]
@codingisacopingstrategy The CODA label is added in the wizard (in EN and FR, other languages will have EN).

For the OFX problem, `account_bank_statement_import` doesn't add the OFX in the `supported formats`.
I think the app have a wrong label. 
Odoo entreprise have a OFX addon, which need the `account_bank_statement_import` addon and there is the OCA one which I pointed earlier (which also depends of  `account_bank_statement_import`.

If you find that it's a bug in this addon feel free to write how to reproduce it.

**Comment by codingisacopingstrategy** [comment]
My bookkeeper says:

> J’ai testé le module pour les coda, il a l’air de fonctionner correctement. Les écritures passées sont correctes et la reconnaissance des factures/fournisseurs fonctionne bien aussi

So that’s great!

**Comment by codingisacopingstrategy** [comment]
Hiya,

Any additional steps required before this can be merged?

Best,

**Review by lmignon — APPROVED** [review]

**Review by sbidoul — APPROVED** [review]
rebased.

**Pull request merged**
