### PR TITLE
[IMP] intrastat_product_hscodes_import: 2023 CN codes

### PR DESCRIPTION
**Pull request by luc-demeyer**
Module l10n_be_intrastat_product, install wizard: 2023 CN codes.

### CODE REVIEW

**Comment by luc-demeyer** [comment]
@sbidoul 
pre-commit fails : AttributeError: 'EntryPoints' object has no attribute 'get'
It looks like the 14.0 branch of this repo is broken.
Can you have a look ?

**Comment by sbidoul** [comment]
It should be ok after #206 has landed.

**Pull request merged**
