### PR TITLE
[11.0][MIG] l10n_be_mis_reports

### PR DESCRIPTION
**Pull request by sbidoul**
* Includes #64 
* Adds account details

### CODE REVIEW

**Comment by sbidoul** [comment]
cc/ @vdewulf

**Comment by sbidoul** [comment]
cc/ @codingisacopingstrategy

you can add this line in your requirements.txt to install

```
-e git+https://github.com/acsone/l10n-belgium@11.0-mig-mis-reports#egg=odoo11-addon-l10n_be_mis_reports&subdirectory=setup/l10n_be_mis_reports
```

Then test by installing l10n_be_mis_reports, then creating new reports in the MIS Reporting menu, using one of the 3 templates provided by this module.

**Comment by codingisacopingstrategy** [comment]
Hello! I got a Github e-mail about added commits, but it looks like they’ve disappeared again! With the version at 915e3a014b925110f3163366a5daf771b5d98b09 I get errors for now:

screen shot 2018-07-08 at 18 42 35

**Comment by sbidoul** [comment]
@codingisacopingstrategy the error will resolve itself with https://github.com/OCA/mis-builder/pull/108.

In the meantime skip commit 16d3e21033831d1ca5bb1277959929263ac0dcd3

**Comment by codingisacopingstrategy** [comment]
Hmm I tried to get the latest code, rebase and skip 16d3e21 but I still get those errors. I am able to print now though, that wasn’t working before.

BTW a small glitch I noted: when choosing “Belgium Value Added Tax Report Sheet” the dialog that pops up has buttons with img url’s that 404: ``, ``, ``, ``.

screen shot 2018-07-09 at 00 33 12

**Comment by sbidoul** [comment]
The icons issue is resolved in the latest version of mis builder.

Can you hover your mouse on #ERR to view the error message?

**Comment by codingisacopingstrategy** [comment]
The first four errors:

screen shot 2018-07-09 at 10 05 07

The last one:

screen shot 2018-07-09 at 10 05 51

**Comment by sbidoul** [comment]
Can you try with the latest mis-builder? `venv/bin/pip install -U odoo11-addon-mis-builder --pre`, restart Odoo and click upgrade on the mis builder module.

**Comment by codingisacopingstrategy** [comment]
Ah, the checks are now all check-marked!

(the button images are not there though, but that is of lesser importance)

**Comment by sbidoul** [comment]
Pure data modules, migrated trivially from 9 and 10.

**Comment by codingisacopingstrategy** [comment]
I migrated to the merged version, I’ll find out after Q4 if there are any hicks, but it should be fine. Thanks everybody!

**Pull request merged**
