### PR TITLE
[13.0][FIX] Add missing requirements.txt

### PR DESCRIPTION
**Pull request by carmenbianca**
Backported from 14.0.

### CODE REVIEW

**Review by robinkeunen — COMMENTED** [review]
We do not maintain a 13.0 version

**Comment by carmenbianca** [comment]
@robinkeunen This is a PR against the OCA ;) I did this as a courtesy.

**Comment by robinkeunen** [comment]
@carmenbianca oupsie, good on you. I thought we were on another repo.

**Comment by sbidoul** [comment]
We should rather upgrade to the latest repo template and answer yes to the "generate requirements.txt" question.

**Comment by sbidoul** [comment]
Hm, in 13 this bit is missing from the pre-commit config so I made https://github.com/OCA/oca-addons-repo-template/pull/153

**Comment by sbidoul** [comment]
Done in #148

**Pull request closed without merging**
