### PR TITLE
add l10n_be_coa_multilang to 8.0 branch

### PR DESCRIPTION
**Pull request by luc-demeyer**

### CODE REVIEW

**Comment by sbidoul** [comment]
Hi Luc,

Glad to have you on board!

I just created the 8.0 branch.

Does this version of l10n_be_coa_multilang work on 7.0 too? In which case I'll merge it into 7.0 and forward-port it to 8.0.

If not what do you think about doing a PR for the 7.0 version and then the adaptations for 8.0 so we have both on github?

Last, would you like to investigate the travis build errors. Most of them are pep8/flake8 issues that are easy to fix (I'm not a huge fan of 80 characters lines but that's the OCA rule...). And there is one error about report.account.report_financial that needs to be investigated.

Thanks!

**Comment by sbidoul** [comment]
Before resubmitting, don't forget to merge the 8.0 branch into yours to get the latest travis config file.

**Comment by luc-demeyer** [comment]
Stephane, 

The ‘l10n_be_coa_multilang’ release for which I submitted a PR will only work as from 8.0 onwards.

Do you still expect any action from me for merge into the 8.0 branch or will you do it ?

Older versions (6.0, 6.1, 7.0) of this module are published via our Launchpad branches that are registered on apps.odoo.com (also the 8.0 version is there via our ‘trunk’ Launchpad branch).

I had to make a couple of changes to adapt this module for 8.0.

I also spent a bit of time to make the module PEP8 compliant (except for the 80 character limit since that makes the code in many cases harder to read and maintain, hence I think it’s better to initiate this debate in the OCA than to stick to a rule that originated probably from the punch card time). 

At this point in time, I don’t intend to work on the V7 version of l10n_be_coa_multilang to make it PEP8 compliant and to make an OCA/l10n-belgium PR since we have so many other priorities to work on. 

Regards,

Luc

P.S.

I’ll put the analysis of the travis build errors on my todo list. 

 http://www.noviat.com/ www.noviat.com

Rusatiralaan 1, 1083 Brussel

+32 2 808 86 38

**Comment by sbidoul** [comment]
Can you just merge the 8.0 branch into yours to get the correct travis.yml file?

Then I'll rebase it on the 8.0 branch when travis is happy.

For the record the discussion regarding line length took place there: https://github.com/OCA/maintainer-quality-tools/issues/46

**Comment by luc-demeyer** [comment]
Stefan, 

I had a look to that line length discussion.  

I honestly don’t see the sense of spending/loosing time on this crazy old style 80 character limit but it looks like the OCA techies have taken a decision. 

There is no single module from Odoo themselves that comes even close to PEP8 compliancy.

When creating new modules we regularly do some cut & paste from code blocks from Odoo (especially for a localization module).

I’ll keep the ‘l10n_be_coa_multilang’ module on our Launchpad branch for the moment and see whenever I find time and motivation to comply to this line length thing for this particular module. 

This module has a  massive number of line length issues since I started the module a few years ago from the ‘l10n_be’ module which has a number of (technically not so  nice) wizards that will become harder to read/maintain when dogmatically breaking up the lines.

Regards,

Luc

 http://www.noviat.com/ www.noviat.com

Rusatiralaan 1, 1083 Brussel

+32 2 808 86 38

**Comment by sbidoul** [comment]
Closed automatically because master branch removed

**Pull request closed without merging**
