### PR TITLE
[14.0][MIG] 10n_be_partner_kbo_bce

### PR DESCRIPTION
**Pull request by StefanRijnhart**
Trivial migration without any code change.

### CODE REVIEW

**Comment by StefanRijnhart** [comment]
Runbot says "docker: Error response from daemon: pull access denied for oca-l10n-belgium, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.". Does anybody know how that can that be solved?

**Comment by sbidoul** [comment]
@StefanRijnhart thanks for the migration. Could you rebase to see if we now have a green build ?

**Comment by StefanRijnhart** [comment]
@sbidoul it worked!

**Review by sbidoul — APPROVED** [review]

**Comment by sbidoul** [comment]
Thanks! I'll let a few days pass before merging so @luc-demeyer has a chance to chime in if he had other changes in mind for v14.

**Review by luc-demeyer — APPROVED** [review]

**Pull request merged**
