### PR TITLE
[14.0] l10n_be_mis_reports: add vat report

### PR DESCRIPTION
**Pull request by huguesdk**

### CODE REVIEW

**Review by remytms — APPROVED** [review]
LGTM

**Comment by remytms** [comment]
I just rebased on top of the 14.0 branch.

**Review by houssine78 — APPROVED** [review]
LGTM

**Comment by houssine78** [comment]
@sbidoul this module is ready to be merge now ;)

**Comment by sbidoul** [comment]
/ocabot merge minor

Great work, thanks @vdewulf & co!

**Pull request merged**
