### PR TITLE
12.0 mig account bank statement import coda

### PR DESCRIPTION
**Pull request by houssine78**
[MIG] this PR ports the import coda module to v12. Small adjustments have been made due to changes between Odoo 11 and 12.

It has been tested by our side.

### CODE REVIEW

**Comment by houssine78** [comment]
Hi @sbidoul here is the PR that ports the module to v12. It would be great if you could have a look. Thanks !

**Review by ThomasBinsfeld — APPROVED** [review]
LGTM. Could you fix the flake8/pylint errors please?

**Comment by sbidoul** [comment]
@lmignon could you help @houssine78 greenifying this PR if needed?

**Comment by lmignon** [comment]
@sbidoul for sure....

**Comment by lmignon** [comment]
fixed in #80

**Comment by sbidoul** [comment]
superseded by #80

**Pull request closed without merging**
