### PR TITLE
OCA Transbot updated translations from Transifex

### PR DESCRIPTION
**Pull request by lmignon**

### CODE REVIEW

**Comment by yvaucher** [comment]
:+1:

**Comment by pedrobaeza** [comment]
So translations are proposed as PR in your tx-pull branch or this is only a test?

**Comment by lmignon** [comment]
@pedrobaeza The translations have been pushed by tx-pull to a test repository and I've created a PR from this repository. I've updated tx-pull to be able to provide an alternative org where to push the translations so it's possible for a user without commit right on a repository to get the translations and do a  manual PR with the translations...

**Comment by pedrobaeza** [comment]
Ah, OK, thanks for the clarification.

**Comment by sbidoul** [comment]
:+1:

**Comment by adrienpeiffer** [comment]
:+1:

**Pull request merged**
