### PR TITLE
[16.0][MIG] l10n_be_vat_reports

### PR DESCRIPTION
**Pull request by victor-champonnois**
Suggestions for making my changes cleaner are welcome!

this PR also port the changes in https://github.com/OCA/l10n-belgium/pull/217

### CODE REVIEW

**Review by remytms — APPROVED** [review]
Quick review. LGTM.

**Review by vdewulf — APPROVED** [review]
I tested functionnally this module in v16. It works exactly like in v12 (the version I know best).

**Review by robinkeunen — APPROVED** [review]
I do not understand tag's behaviour but trusting the review by @remytms and @vdewulf 's review and test. The rests looks good.

**Pull request merged**
