### PR TITLE
[10.0] mig l10n_be_mis_reports

### PR DESCRIPTION
**Pull request by sbidoul**
TODO

- [x] rework styles

Depends on 
- [x] mis_builder 10.0 https://github.com/OCA/account-financial-reporting/pull/239

### CODE REVIEW

**Comment by sbidoul** [comment]
Implemented v9/10 styles. This one is now ready.

**Comment by pedrobaeza** [comment]
Happy birthday, Stéphane! Don't work on your day, hehe.

**Comment by sbidoul** [comment]
Thanks Pedro!

**Comment by sbidoul** [comment]
@adrienpeiffer can you review?

**Review by adrienpeiffer — APPROVED** [review]
:+1:

**Pull request merged**
