### PR TITLE
[16.0][MIG] l10n_be_mis_reports_xml

### PR DESCRIPTION
**Pull request by victor-champonnois**
Not tested functionally

task : https://gestion.coopiteasy.be/web#id=10791&action=475&active_id=492&model=project.task&view_type=form&menu_id=

### CODE REVIEW

**Review by carmenbianca — APPROVED** [review]
LGTM awaiting functional testing

**Review by len-foss — APPROVED** [review]
Functional review: I used the XML file on Intervat for this trimester and it's correct.

**Comment by regispirard** [comment]
Nice ! Thank you @robinkeunen !

**Pull request merged**
